import { Geist, Geist_Mono, DynaPuff } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const dynaPuff = DynaPuff({
  variable: "--font-dyna-puff",
  subsets:["cyrillic-ext", "latin", "latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={dynaPuff.className}>
        {children}
      </body>
    </html>
  );
}
